### ISSUE TITLE
i have a question

### ISSUE THREAD

**Issue by Jojo09092007** [arachnist/nibylandia#1]
What is the latest working raspberry pi 3 config, and which pull request is it, Thanks in advance

**Comment by Jojo09092007** [comment]
For context I downloaded the sd image for nixos, and I wanted to flash akamanto to it. My approach is documented on this repo: https://github.com/Jojo09092007/UPDATE-KODAK-3D-PRINTER

**Comment by Jojo09092007** [comment]
It builds but it complains about agenixinstall

**Comment by Jojo09092007** [comment]
![Screenshot_2024-07-11-10-07-06-35_99c04817c0de5652397fc8b56c3b3817.jpg](https://github.com/arachnist/nibylandia/assets/92645124/d20a303c-d824-4066-a84f-f2f211246925)

This is the error i hope it helps

**Comment by arachnist** [comment]
you'll need to remove - at least - these lines:
https://github.com/arachnist/nibylandia/blob/d1a1cf11420ce98d09d072b6aa6c297a07b48106/modules/common.nix#L18
https://github.com/arachnist/nibylandia/blob/d1a1cf11420ce98d09d072b6aa6c297a07b48106/modules/common.nix#L72-L83

**Comment by Jojo09092007** [comment]
I will try that, Thanks.

**Comment by Jojo09092007** [comment]
![IMG_20240716_104643.jpg](https://github.com/user-attachments/assets/f6f2b241-b9e2-4d26-b40d-6d42ff7f0162)

Now i have this error, the lower one i fixed, but the upper one I cant find.

**Comment by Jojo09092007** [comment]
I am just doing this as a school project, and i would really appreciate the help.

**Comment by arachnist** [comment]
@Jojo09092007 I'm sorry, I can't really help you. Because of peculiarities of Nix language, the syntax error can be in completely unrelated place, and since I can't see your code (it appears you didn't fork and commit/pushed your changes anywhere), you're on your own. If you don't have experience with NixOS, you'd probably be better off with [MainsailOS](https://docs-os.mainsail.xyz/getting-started)

**Comment by Jojo09092007** [comment]
Sorry for not sharing: https://github.com/Jojo09092007/UPDATE-KODAK-3D-PRINTER 
This is the repo, anyway I will probably switch to MainsailOS, Thanks for the help.

**Comment by Jojo09092007** [comment]
![Screenshot_2024-08-09-11-45-32-85_dc00545bd3b8828f033a02ac25b2d36d.jpg](https://github.com/user-attachments/assets/29c9886f-f57c-4933-89cf-9b8771de8164)

![Screenshot_2024-08-09-11-45-40-52_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/user-attachments/assets/0142595f-55e5-4b23-ac6b-b89e709f25a0)

Do these correspont to one and another or how are these connected?
